name: CD of ___MODULENAME___
on:
  push:
    paths:
      - '___LATEST.JSON___'
  workflow_dispatch:
jobs:
  publish-module:
    name: Publish to PSGallery
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build-Test
      run: |
        . .\build.ps1
        Start-ModuleInstallationBuild
        Set-ModuleInstallationTestReport
        Push-ModuleInstallationTestReport -Email ${{ secrets.EMAIL_KEY }}
        Add-ModuleInstallationVersionTag
    - name: Publish
      if: success()
      run: |
        Import-Module ___MODULENAME___ -Force
        Publish-Module -Name ___MODULENAME___ -NuGetApiKey ${{ secrets.NUGET_API_KEY }} -Force